profiles:
- name: Qt5.3
  platform: Ubuntu1404
  commands: standard
  setup:
    - qt530_gcc490

actions:
- name: prepare
  standard:
  - 'qmake'

- name: build
  standard:
  - 'make'

- name: test
  standard:
  - 'make check'
